server_name: 'Lif-2'
#thermal_device: 0
thermal_device: "gst-launch-1.0 v4l2src device=/dev/v4l/by-id/usb-GroupGets_PureThermal__fw:v1.3.0__003a0029-5008-564e-3536-203400000000-video-index0 ! video/x-raw,format=GRAY16_LE ! appsink"
video_device: "/dev/v4l/by-id/usb-CNFFH36O30144000DB52_Integrated_Webcam_0x0001-video-index0"
data_folder: "video"